version: '3.8'
services:
  postgres:
    container_name: postgres_request
    image: postgres:10.5

    env_file:
      - .env
    restart: always
    ports: 
      - "5433:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  